spring:
  application:
    name: kiranastore
  data:
    mongodb:
      uri: mongodb+srv://srinjoy:ZmUiUFEeAJLCkQZQ@cluster0.qkd0v.mongodb.net/kirana?retryWrites=true&w=majority
      database: kirana
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      time-to-live: 60000
application:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

